version: "2.1"
services:
  devshop:
    build:
      context: .
    image: devshop/local
    container_name: devshop
    hostname: devshop.local.computer
    volumes:
      - ./config:/config

      # Allow development of s6 config
      - ./root/etc/s6-overlay/s6-rc.d/init-devshop-config:/root/etc/s6-overlay/s6-rc.d/init-devshop-config

      # Allow development of devshop.platform
      - ./root/app:/root/app

    environment:
      - PUID=${PGUID:-1000}
      - PGID=${PGUID:-1000}
      - TZ=America/New_York
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped