#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DEVSHOP_APP_DIR=/app/devshop
SERVER_HOSTNAME=$(hostname -f)
ANSIBLE_CONFIG_DIR=/config/devshop/ansible

echo "DEVSHOP | Hello! I am the run script and I am starting now."

mkdir -p \
    /config/devshop

# If default ansible config doesn't exist yet, copy from defaults.
if [ ! -d ${ANSIBLE_CONFIG_DIR} ]; then
    cp -rf /defaults/ansible ${ANSIBLE_CONFIG_DIR}
fi
if [ ! -d /etc/ansible ]; then
    ln -sf ${ANSIBLE_CONFIG_DIR} /etc/ansible
fi

echo "Preparing config for DevShop Server: ${SERVER_HOSTNAME}"
HOSTVARS_DIR="/etc/ansible/hostvars/${SERVER_HOSTNAME}"

mkdir -p $HOSTVARS_DIR
if [ ! -f "$HOSTVARS_DIR/secrets.yml" ]; then
    cat > "$HOSTVARS_DIR/secrets.yml" <<EOT
mysql_root_password: '$(tr -dc 'a-zA-Z0-9~!@#$%^&*_()+}{?></";.,[]=-' </dev/urandom | fold -w 32 | head -n 1)'
EOT
fi
if [ ! -f "$HOSTVARS_DIR/vars.yml" ]; then
    cat > "$HOSTVARS_DIR/vars.yml" <<EOT
devshop_host_hostname: $SERVER_HOSTNAME 
EOT
fi

# Install
# If default ansible config doesn't exist yet, copy from defaults.
if [ ! -d ${ANSIBLE_CONFIG_DIR} ]; then
    cp -rf /defaults/ansible ${ANSIBLE_CONFIG_DIR}
fi

ansible --version


#
## permissions
#lsiown -R abc:abc \
#    /config \
#    /app/www/public/tmp
