#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DEVSHOP_APP_DIR=/app/devshop
SERVER_HOSTNAME=$(hostname -f)
ANSIBLE_CONFIG_DIR=/config/devshop/ansible

mkdir -p \
    /config/devshop

# If default ansible config doesn't exist yet, copy from defaults.
if [ ! -d ${ANSIBLE_CONFIG_DIR} ]; then
    cp -rf /defaults/ansible ${ANSIBLE_CONFIG_DIR}
fi
if [ ! -f /etc/ansible ]; then
    ln -sf ${ANSIBLE_CONFIG_DIR} /etc/ansible
fi

echo "Preparing config for DevShop Server: ${SERVER_HOSTNAME}"
mkdir -p /etc/ansible/hostvars/${SERVER_HOSTNAME}
if [ ! -f ${ANSIBLE_CONFIG_DIR}/hostvars/{$SERVER_HOSTNAME}/secrets.yml ]; then
    cat > ${ANSIBLE_CONFIG_DIR}/hostvars/{$SERVER_HOSTNAME}/secrets.yml <<EOT
devshop_host_hostname: $SERVER_HOSTNAME 
mysql_root_password: '$(tr -dc 'a-zA-Z0-9~!@#$%^&*_()+}{?></";.,[]=-' </dev/urandom | fold -w 32 | head -n 1)'
EOT
fi
if [ ! -f ${ANSIBLE_CONFIG_DIR}/hostvars/{$SERVER_HOSTNAME}/vars.yml ]; then
    cat > ${ANSIBLE_CONFIG_DIR}/hostvars/{$SERVER_HOSTNAME}/vars.yml <<EOT
devshop_host_hostname: $SERVER_HOSTNAME 
EOT
fi

# Install
# If default ansible config doesn't exist yet, copy from defaults.
if [ ! -d ${ANSIBLE_CONFIG_DIR} ]; then
    cp -rf /defaults/ansible ${ANSIBLE_CONFIG_DIR}
fi

# Install prereqs

# permissions
lsiown -R abc:abc \
    /config \
    /app/www/public/tmp
